@HostAddress = http://localhost:5021
@RecipeId = 2
@IngredientId = 2

GET {{HostAddress}}/
Accept: application/json

### Recipes

### GET recipes
GET {{HostAddress}}/recipes
Accept: application/json

### GET recipes/id
GET {{HostAddress}}/recipes/{{RecipeId}}
Accept: application/json

### POST recipe
POST {{HostAddress}}/recipes
Content-Type: application/json

{
    "title": "Bolo de cenoura",
    "instructions": "Bata os ovos, óleo e cenoura no liquidificador. Misture com o restante seco. Asse 40min a 180°C.",
    "prepTimeMinutes": 60,
    "servings": 8
}

### PUT recipe
PUT {{HostAddress}}/recipes/{{RecipeId}}
Content-Type: application/json

{
    "title": "Bolo de cenoura (editado)",
    "instructions": "Bata os ovos, óleo e cenoura no liquidificador. Misture com o restante seco. Asse 40min a 180°C. Cubra com calda de chocolate.",
    "prepTimeMinutes": 75,
    "servings": 10
}

### DELETE recipe
DELETE {{HostAddress}}/recipes/{{RecipeId}}
Accept: application/json

### POST ingredient na recipe
POST {{HostAddress}}/recipes/{{RecipeId}}/ingredients
Content-Type: application/json

{
    "ingredientId": 2,
    "quantity": 3,
    "unit": "un"
}

### DELETE ingredient da recipe
DELETE {{HostAddress}}/recipes/{{RecipeId}}/ingredients/{{IngredientId}}
Accept: application/json

### Ingredients

### GET ingredients
GET {{HostAddress}}/ingredients
Accept: application/json

### GET ingredients/id
GET {{HostAddress}}/ingredients/{{IngredientId}}
Accept: application/json

### POST ingredient
POST {{HostAddress}}/ingredients
Content-Type: application/json

{
    "name": "Cenoura"
}

### PUT ingredient
PUT {{HostAddress}}/ingredients/{{IngredientId}}
Content-Type: application/json

{
    "name": "Cenoura ralada"
}

### DELETE ingredient
DELETE {{HostAddress}}/ingredients/{{IngredientId}}
Accept: application/json